# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'part3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for part3

  target 'part3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'part3UITests' do
    # Pods for testing
  end
 pod 'FSCalendar'  
end
